"""fix typo in godparent referral column

Revision ID: 242be66d6745
Revises: 578c4f5cbb86
Create Date: 2017-10-12 20:02:02.013059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '242be66d6745'
down_revision = '578c4f5cbb86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('godparent', sa.Column('referral_name', sa.String(length=64), nullable=True))
    op.drop_column('godparent', 'referal_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('godparent', sa.Column('referal_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('godparent', 'referral_name')
    # ### end Alembic commands ###
