"""rename pic_url as photo_url

Revision ID: 2b817e859a2d
Revises: b59c6429de6c
Create Date: 2017-03-19 14:27:49.715936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b817e859a2d'
down_revision = 'b59c6429de6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('child', sa.Column('photo_url', sa.String(length=3000), nullable=True))
    op.drop_column('child', 'pic_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('child', sa.Column('pic_url', sa.VARCHAR(length=3000), autoincrement=False, nullable=True))
    op.drop_column('child', 'photo_url')
    # ### end Alembic commands ###
