"""add project and child to proejct table

Revision ID: 3bf2b2fe062d
Revises: 7665dea01c37
Create Date: 2017-10-07 18:52:02.613907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bf2b2fe062d'
down_revision = '7665dea01c37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.Column('project_name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('child_to_project',
    sa.Column('child_id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.Column('project_id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('child_id', 'project_id')
    )
    op.drop_column(u'child', 'project')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'child', sa.Column('project', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_table('child_to_project')
    op.drop_table('project')
    # ### end Alembic commands ###
