"""change project_name to name and increase max characters

Revision ID: 3fe5c7eded85
Revises: cf4525e18940
Create Date: 2017-10-08 20:00:35.605970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fe5c7eded85'
down_revision = 'cf4525e18940'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('name', sa.String(length=80), nullable=False))
    op.drop_column('project', 'project_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('project_name', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_column('project', 'name')
    # ### end Alembic commands ###
