"""add GodparentToProject table

Revision ID: 578c4f5cbb86
Revises: 6462fc3c6181
Create Date: 2017-10-09 22:17:54.819206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '578c4f5cbb86'
down_revision = '6462fc3c6181'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('godparent_to_project',
    sa.Column('godparent_id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.Column('project_id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['godparent_id'], ['godparent.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('godparent_id', 'project_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('godparent_to_project')
    # ### end Alembic commands ###
