"""add birth_date_accuracy to Child model

Revision ID: 59d9fb049d92
Revises: b7a6f29ccc56
Create Date: 2017-10-30 21:22:58.452308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59d9fb049d92'
down_revision = 'b7a6f29ccc56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('child', sa.Column('birth_date_accuracy', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('child', 'birth_date_accuracy')
    # ### end Alembic commands ###
