"""add referal_name to Godparent and increase char limit

Revision ID: 6462fc3c6181
Revises: 3fe5c7eded85
Create Date: 2017-10-09 22:10:14.110114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6462fc3c6181'
down_revision = '3fe5c7eded85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('godparent', sa.Column('referal_name', sa.String(length=64), nullable=True))
    op.alter_column('godparent', 'first_name',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('godparent', 'last_name',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('godparent', 'last_name',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('godparent', 'first_name',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.drop_column('godparent', 'referal_name')
    # ### end Alembic commands ###
