"""add school name

Revision ID: 7f7850bc2934
Revises: 59d9fb049d92
Create Date: 2018-11-05 23:48:04.096953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f7850bc2934'
down_revision = '59d9fb049d92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('child', sa.Column('school_name', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('child', 'school_name')
    # ### end Alembic commands ###
