"""group and permission tables

Revision ID: 882ee32276dc
Revises: 242be66d6745
Create Date: 2017-10-15 22:42:11.862655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '882ee32276dc'
down_revision = '242be66d6745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permission',
    sa.Column('id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_to_permission',
    sa.Column('group_id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.Column('permission_id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'permission_id')
    )
    op.create_table('user_to_group',
    sa.Column('user_id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.Column('group_id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.add_column(u'user', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column(u'user', sa.Column('modified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'user', 'modified_at')
    op.drop_column(u'user', 'created_at')
    op.drop_table('user_to_group')
    op.drop_table('group_to_permission')
    op.drop_table('permission')
    op.drop_table('group')
    # ### end Alembic commands ###
