"""add gender to Child and change photo to LargeBinary type

Revision ID: acface0f3858
Revises: 242be66d6745
Create Date: 2017-10-22 13:06:22.607387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acface0f3858'
down_revision = '242be66d6745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('child', sa.Column('gender', sa.String(length=32), nullable=True))
    op.add_column('child', sa.Column('photo', sa.LargeBinary(), nullable=True))
    op.drop_column('child', 'photo_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('child', sa.Column('photo_url', sa.VARCHAR(length=3000), autoincrement=False, nullable=True))
    op.drop_column('child', 'photo')
    op.drop_column('child', 'gender')
    # ### end Alembic commands ###
