"""init all tables

Revision ID: b59c6429de6c
Revises: 
Create Date: 2017-02-04 15:59:14.968595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b59c6429de6c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('child',
    sa.Column('id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.Column('pic_url', sa.String(length=3000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('first_name', sa.String(length=32), nullable=False),
    sa.Column('last_name', sa.String(length=32), nullable=False),
    sa.Column('nick_name', sa.String(length=32), nullable=False),
    sa.Column('birth_date', sa.DateTime(), nullable=False),
    sa.Column('nationality', sa.String(length=200), nullable=True),
    sa.Column('guardian_type', sa.String(length=50), nullable=True),
    sa.Column('guardian_fname', sa.String(length=32), nullable=True),
    sa.Column('guardian_lname', sa.String(length=32), nullable=True),
    sa.Column('number_of_siblings', sa.Integer(), nullable=True),
    sa.Column('siblings_in_project', sa.String(), nullable=True),
    sa.Column('school_class', sa.String(length=50), nullable=True),
    sa.Column('school_attendance', sa.String(length=50), nullable=True),
    sa.Column('volunteer_task', sa.String(), nullable=True),
    sa.Column('situation', sa.String(), nullable=True),
    sa.Column('godparent_status', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('godparent',
    sa.Column('id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=False),
    sa.Column('last_name', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=False),
    sa.Column('last_name', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('child_to_godparent',
    sa.Column('child_id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.Column('godparent_id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ),
    sa.ForeignKeyConstraint(['godparent_id'], ['godparent.id'], ),
    sa.PrimaryKeyConstraint('child_id', 'godparent_id')
    )
    op.create_table('message',
    sa.Column('id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.Column('godparent_id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.Column('child_id', sa.dialects.postgresql.UUID(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('text_content', sa.String(length=8000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('sent_ok', sa.Boolean(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ),
    sa.ForeignKeyConstraint(['godparent_id'], ['godparent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('child_to_godparent')
    op.drop_table('user')
    op.drop_table('godparent')
    op.drop_table('child')
    # ### end Alembic commands ###
