"""rename child.activity to child.is_active

Revision ID: b9fff1002a53
Revises: ef7a4372461e
Create Date: 2017-02-03 20:19:27.804829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9fff1002a53'
down_revision = 'ef7a4372461e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('child', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('child', 'activity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('child', sa.Column('activity', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('child', 'is_active')
    # ### end Alembic commands ###
